### ISSUE TITLE
Support Enums

### ISSUE THREAD

**Issue by huntiep** [maghoff/bart#18]
What are your thoughts on supporting enums in Bart? As an example, say that I have this setup:
```rust
enum Item {
    Struct(String),
    Enum(String),
    Trait(String),
}

#[derive(BartDisplay)]
#[template = "doc.html"]
struct Tmpl {
    items: Vec<Item>,
}
```
```html
{{#items}}
<p class="{{TYPE}}">{{.0}}</p>
{{/items}}
```

I want the class to be different based on what variant of the enum I have. I saw that function call syntax was added, so would this be the best solution:
```rust
impl Item {
    pub fn item_type(&self) -> &'static str {
        match *self {
            Item::Struct(_) => "struct",
            Item::Enum(_) => "enum",
            Item::Trait(_) => "trait",
        }
    }
}
```
```html
{{#items}}
<p class="{{.item_type()}}">{{.0}}</p>
{{/items}}
```

Or would an enum-specific solution be better?

This is just a hypothetical right now, but it might be useful to think about.

**Comment by maghoff** [comment]
This is a fully working variant of your case above:

```rust
#[macro_use] extern crate bart_derive;

enum Item {
    Struct(String),
    Enum(String),
    Trait(String),
}

#[derive(BartDisplay)]
#[template_string = "
{{#items}}
    {{#.destructure().}}
        <p class=\"{{.0}}\">{{.1}}</p>
    {{/.destructure()}}
{{/items}}
"]
struct Tmpl {
    items: Vec<Item>,
}

impl Item {
    fn destructure(&self) -> (&'static str, &str) {
        match self {
            &Item::Struct(ref x) => ("struct", &x),
            &Item::Enum(ref x) => ("enum", &x),
            &Item::Trait(ref x) => ("trait", &x),
        }
    }
}

fn main() {
    print!("{}", &Tmpl {
        items: vec! [
            Item::Struct("test struct".to_owned()),
            Item::Enum("test enum".to_owned()),
            Item::Trait("test trait".to_owned()),
        ]
    });
}
```

The enum you have chosen as an example is a special case in that it is completely homogenous; it makes sense to treat each case the same. For this special case, destructuring like above can be appropriate.

When the enum is more heterogeneous, perhaps it is more useful to explode it into a tuple of options, something like:

```
enum E {
    A(String),
    B { x: i32 },
    C,
}

struct HelperStruct {
    x: i32
}

impl E {
    fn explode(&self) -> (Option<String>, Option<HelperStruct>, Option<()>) {...}
}
```

That's a first approximation anyway :)

As it is, I'm not planning any specific enum support in bart. If you have a real use-case and you are not satisfied with resolving it like above, please bring it up :)

**Comment by maghoff** [comment]
Here is a fleshed out `explode`-implementation, which actually works:

```rust
enum E {
    A(String),
    B { x: i32 },
    C,
}

type _A<'a> = (&'a String);

struct _B<'a> {
    x: &'a i32,
}

struct _C;

struct _explode_E<'a> {
    A: Option<_A<'a>>,
    B: Option<_B<'a>>,
    C: Option<_C>,
}

impl E {
    fn explode(&self) -> _explode_E {
        match self {
            &E::A(ref x) => _explode_E { A: Some(x), B: None, C: None },
            &E::B { ref x } => _explode_E { A: None, B: Some(_B { x }), C: None },
            &E::C => _explode_E { A: None, B: None, C: Some(_C) },
        }
    }
}

#[derive(BartDisplay)]
#[template_string="
{{#x.explode().}}
{{#.A}}Variant A: {{.}}{{/.A}}
{{#.B}}Variant B: {{.x}}{{/.B}}
{{#.C}}Variant C{{/.C}}
{{/x.explode()}}
"]
struct TestEnum {
    x: E
}
```

I _think_ all this could be generated by an additional derive-style macro, for the enum.

I will now close this issue; it is _possible_ to use enums with Bart without changing the language or implementation. I am not adverse to change these things, but I prefer it to be advised by real use cases :) Thanks for bringing this up.

**Comment by huntiep** [comment]
That's what I was thinking. I'm actually starting to work with enums now, so I think I'll try writing an Explode proc macro and see how that feels. Thanks for thinking about it!
